import{a as E,S as $}from"./assets/vendor-CW10_Hpq.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const H="46806547-3cbb9c5e78d8f101f788426f8",P="https://pixabay.com/api/",S=15;async function m(t,s=1){const n=`${P}?key=${H}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${S}&page=${s}`,o=await E.get(n);if(o.status!==200)throw new Error("Failed to fetch images");return{images:o.data.hits.map(({webformatURL:e,largeImageURL:r,tags:l,likes:b,comments:L,views:v,downloads:w})=>({webformatURL:e,largeImageURL:r,tags:l,likes:b,comments:L,views:v,downloads:w})),totalHits:o.data.totalHits}}function h(t,s=!1){const n=document.querySelector(".gallery"),o=t.map(e=>`
        <div class="image-card">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
            </a>
            <div class="image-info">
                <span>👍 ${e.likes}</span>
                <span>💬 ${e.comments}</span>
                <span>👁 ${e.views}</span>
                <span>⬇ ${e.downloads}</span>
            </div>
        </div>
    `).join("");s?n.insertAdjacentHTML("beforeend",o):n.innerHTML=o}function d(t){iziToast.show({title:"Error",message:t,color:"red",position:"topRight"})}const p=document.querySelector("#search-form"),y=document.querySelector(".gallery"),u=document.getElementById("loader"),a=document.createElement("button");a.textContent="Load more";a.classList.add("load-more");y.insertAdjacentElement("afterend",a);let g=new $(".gallery a"),c="",i=1,f=0;p.addEventListener("submit",async t=>{var s;if(t.preventDefault(),c=(s=p.elements.searchQuery)==null?void 0:s.value.trim(),!c){d("Please enter a valid search query");return}i=1,a.style.display="none",y.innerHTML="",u.style.display="block";try{const{images:n,totalHits:o}=await m(c,i);f=o,h(n),g.refresh(),f>i*15&&(a.style.display="block")}catch(n){d(n.message)}finally{u.style.display="none"}});a.addEventListener("click",async()=>{i+=1,u.style.display="block";try{const{images:t}=await m(c,i);h(t,!0),g.refresh(),i*15>=f?(a.style.display="none",d("We're sorry, but you've reached the end of search results.")):q()}catch(t){d(t.message)}finally{u.style.display="none"}});function q(){const{height:t}=y.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
